# Ejercicio 2

In [1]:
import sys
sys.path.append("../src")

import numpy as np
import pandas as pd

from lista4.data import load_csv
from lista4.models import fit_linear
from lista4.metrics import riesgo_cuadratico

## (a)-(c) Ajuste, correlaciones y tabla resumen

In [2]:
archivos = ["experimento_2_a.csv", "experimento_2_b.csv", "experimento_2_c.csv"]

filas = []
for nombre in archivos:
    df = load_csv(nombre)
    x1 = df["x1"].values
    x2 = df["x2"].values
    y = df["y"].values
    X12 = df[["x1", "x2"]].values

    corr_x1_x2 = np.corrcoef(x1, x2)[0, 1]

    modelo_x1 = fit_linear(x1, y)
    modelo_x12 = fit_linear(X12, y)

    R_x1 = riesgo_cuadratico(y, modelo_x1.predict(x1.reshape(-1, 1)))
    R_x12 = riesgo_cuadratico(y, modelo_x12.predict(X12))

    filas.append({
        "archivo": nombre,
        "corr(x1,x2)": corr_x1_x2,
        "R_x1": R_x1,
        "R_x1_x2": R_x12,
        "beta1": modelo_x12.coef_[0],
        "beta2": modelo_x12.coef_[1],
    })

tabla_2 = pd.DataFrame(filas)
tabla_2

               archivo  corr(x1,x2)      R_x1   R_x1_x2     beta1     beta2
0  experimento_2_a.csv     0.999760  1.029350  1.025907  5.957231 -2.900650
1  experimento_2_b.csv     0.999779  1.061539  1.059304  0.606315  2.325776
2  experimento_2_c.csv     0.999821  1.141281  1.140041  4.903450 -1.911232

## (d) Delta R por archivo

In [3]:
tabla_2["delta_R"] = tabla_2["R_x1"] - tabla_2["R_x1_x2"]
tabla_2

,archivo,"corr(x1,x2)",R_x1,R_x1_x2,beta1,beta2,delta_R
0,experimento_2_a.csv,0.999760,1.029350,1.025907,5.957231,-2.900650,0.003443
1,experimento_2_b.csv,0.999779,1.061539,1.059304,0.606315,2.325776,0.002235
2,experimento_2_c.csv,0.999821,1.141281,1.140041,4.903450,-1.911232,0.001240

## (e) Rango de beta1, beta2 y delta_R entre los tres archivos

In [4]:
def rango(z):
    return np.max(z) - np.min(z)

rango_beta1 = rango(tabla_2["beta1"].values)
rango_beta2 = rango(tabla_2["beta2"].values)
rango_deltaR = rango(tabla_2["delta_R"].values)

print("rango(beta1) =", rango_beta1)
print("rango(beta2) =", rango_beta2)
print("rango(delta_R) =", rango_deltaR)

rango(beta1) = 5.350916024405555
rango(beta2) = 5.226425956586279
rango(delta_R) = 0.0022033146837794337

## (f) Comparación

In [5]:
print(tabla_2[["archivo", "corr(x1,x2)", "R_x1", "R_x1_x2", "delta_R", "beta1", "beta2"]])
print()
print("rango(delta_R) =", rango_deltaR)
print("rango(beta1)   =", rango_beta1)
print("rango(beta2)   =", rango_beta2)

               archivo  corr(x1,x2)      R_x1   R_x1_x2   delta_R     beta1  \
0  experimento_2_a.csv     0.999760  1.029350  1.025907  0.003443  5.957231
1  experimento_2_b.csv     0.999779  1.061539  1.059304  0.002235  0.606315
2  experimento_2_c.csv     0.999821  1.141281  1.140041  0.001240  4.903450

      beta2
0 -2.900650
1  2.325776
2 -1.911232

rango(delta_R) = 0.0022033146837794337
rango(beta1)   = 5.350916024405555
rango(beta2)   = 5.226425956586279

**Respuesta (f):** se compara si `delta_R` (la mejora en riesgo al agregar x2) es
grande o pequeña frente al rango observado entre archivos, y si `beta1`/`beta2`
cambian de forma similar o muy distinta entre los tres archivos (ver valores
exactos en las celdas anteriores para completar la conclusión con los números
obtenidos).